name: Pull Documentation
on:
  repository_dispatch:
    types: [update]
  workflow_dispatch:
jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: gh-pages
          submodules: 'recursive'
      - name: Update
        run: |
          git submodule foreach git fetch origin gh-pages
          git submodule foreach git checkout gh-pages
          git submodule foreach git reset --hard origin/gh-pages
      - name: Publish
        run: |
          git config --local user.email "git@rhahi.com"
          git config --local user.name "DocumentMultipliexer"
          git add .
          git commit -m "Update submodules" -a || echo "No changes to commit"
          git push origin gh-pages
